version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - WEBSOCKET_URL=ws://localhost:8000/ws
    deploy:
      resources:
        limits:
          memory: 2G

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend

  redis:
    image: redis:6
    ports:
      - "6379:6379" 