version: '3.8'

services:
  backend:
    build: ./src
    ports:
      - "8001:8000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - VESSEL_TRACKING_API_KEY=${VESSEL_API_KEY}
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./src/frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8001
      - REACT_APP_MAPS_KEY=${MAPS_API_KEY}

  postgres:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=routes_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 