import { Book } from '../types/books';

export const books: Book[] = [
  {
    id: 'manutencão-java',
    title: "Manutenção Preditiva com Java: Um Guia Prático para Cientistas de Dados",
    subtitle: "Sistemas Preditivos",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Guia prático de manutenção preditiva com Java",
    coverImage: "/images/books/manutencao-java.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DVCZRW8M",
    category: "Sistemas Preditivos",
    summary: `O livro "Manutenção Preditiva com Java: Um Guia Prático para Cientistas de Dados" aborda a crescente importância da manutenção preditiva, uma abordagem que visa antecipar falhas em equipamentos e sistemas, contribuindo para a redução de custos e aumento da eficiência operacional. Com o avanço tecnológico e a abundância de dados disponíveis, a obra se torna um recurso essencial para cientistas de dados que desejam implementar modelos preditivos eficazes utilizando a linguagem Java. A obra inicia-se com uma introdução aos conceitos fundamentais da manutenção preditiva, enfatizando a relevância da análise de dados e identificação de padrões que podem sinalizar falhas iminentes. Em seguida, os leitores são guiados por capítulos que exploram as principais ferramentas e bibliotecas Java voltadas para algoritmos de aprendizado de máquina e análise estatística. Cada seção é enriquecida com exemplos práticos e estudos de caso que demonstram a aplicação dos conceitos em situações reais. Além disso, o livro discute a integração de sistemas de monitoramento e coleta de dados, ressaltando a importância da qualidade dos dados na eficácia dos modelos preditivos. Os leitores aprenderão sobre como construir pipelines robustos e utilizar técnicas de visualização para interpretar resultados analíticos. Com uma abordagem prática, o guia capacita os profissionais a desenvolver soluções que não apenas preveem falhas, mas também otimizam processos operacionais. Ao longo do texto, há um incentivo à aplicação ativa do conhecimento adquirido em projetos pessoais, promovendo uma aprendizagem engajadora.`,
    pages: 300,
    language: "Português",
    isbn: "B0DVCZRW8M"
  },
  {
    id: 'manutencoes-python',
    title: "Como Prever manutenções Mecânicas com Python?",
    subtitle: "Manutenções Preditivas com Python (Sistemas Preditivos Livro 1)",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Manutenções Preditivas com Python",
    coverImage: "/images/books/manutencoes-python.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DV519HDX",
    category: "Sistemas Preditivos",
    summary: `O livro "Como Prever Manutenções Mecânicas com Python?" aborda a crescente importância da manutenção preditiva no contexto industrial atual, onde a eficiência operacional é fundamental. Destinado a engenheiros, técnicos de manutenção, analistas de dados e estudantes, o eBook oferece uma abordagem prática para otimizar processos industriais por meio da análise preditiva e programação em Python. A obra inicia-se com os conceitos básicos da manutenção preditiva, diferenciando-a das manutenções corretiva e preventiva, além de enfatizar a relevância da coleta e análise de dados. Em seguida, introduz o Python como uma ferramenta essencial para essa análise, apresentando tutoriais que vão desde a instalação do ambiente até o uso de bibliotecas como Pandas e NumPy para manipulação de dados. Nos capítulos seguintes, o foco se volta para técnicas avançadas de previsão utilizando modelos de machine learning, como regressão linear, árvores de decisão e redes neurais. Cada modelo é acompanhado por exemplos práticos e exercícios que permitem ao leitor aplicar os conhecimentos adquiridos. O livro também discute a validação dos modelos e a interpretação dos resultados obtidos, preparando o leitor para implementar soluções eficazes em seu ambiente profissional. Além disso, insights valiosos de especialistas enriquecem o conteúdo apresentado, incentivando os leitores a explorar inovações na área. A obra se propõe não apenas a ensinar previsões de manutenções mecânicas, mas também a inspirar novas possibilidades no campo da manutenção industrial.`,
    pages: 280,
    language: "Português",
    isbn: "B0DV519HDX"
  },
  {
    id: 'python-predictive-insights',
    title: "Python for Predictive Insights: Code Your Way to Data Mastery",
    subtitle: "Sistemas Preditivos",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Master predictive analytics with Python",
    coverImage: "/images/books/python-predictive.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DV2HBF1P",
    category: "Sistemas Preditivos",
    summary: `"Python for Predictive Insights: Code Your Way to Data Mastery" is a vital resource for anyone looking to harness the power of data through Python programming, particularly in the realm of predictive analytics. In today's data-driven landscape, mastering these skills is essential for professionals and enthusiasts alike. The book begins with an introduction to Python, covering fundamental concepts such as syntax, data structures, and essential libraries like Pandas and NumPy that are crucial for effective data manipulation. As readers progress, they will explore various predictive modeling techniques including regression analysis, classification, and clustering. Each chapter is enriched with real-world examples and hands-on exercises that reinforce learning and application of concepts. Advanced topics such as machine learning algorithms, model evaluation, and deployment strategies are also covered, emphasizing the importance of interpreting results and effectively communicating findings. The structured approach of the book allows for a gradual build-up of knowledge, making it accessible to beginners while still offering depth for more experienced practitioners. By engaging with this content, readers will not only learn how to implement predictive models using Python but also gain insights into making informed data-driven decisions in their respective fields. Overall, this book serves as both a technical manual and an invitation to explore the transformative potential of data analytics.`,
    pages: 350,
    language: "English",
    isbn: "B0DV2HBF1P"
  },
  {
    id: 'mastering-predictive-maintenance',
    title: "Mastering Predictive Maintenance: your Blueprint for Software",
    subtitle: "Sistemas Preditivos",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Blueprint for predictive maintenance software",
    coverImage: "/images/books/mastering-predictive.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DV2R31W6",
    category: "Sistemas Preditivos",
    summary: `Mastering Predictive Maintenance: Your Blueprint for Software Development delves into the critical role of predictive maintenance in modern industry, emphasizing its significance in enhancing operational efficiency and reducing downtime. The book outlines a comprehensive approach to developing software solutions that facilitate predictive maintenance, starting with an understanding of common mechanical failures and their implications. Key topics include the selection of equipment for monitoring, data sources such as sensors and maintenance logs, and the importance of structuring a robust database. The text covers essential data preprocessing techniques like cleaning, normalization, handling missing values, and converting categorical data into numerical formats. Visualization methods using libraries like Matplotlib and Seaborn are discussed to uncover patterns and correlations within the data. The book provides an overview of machine learning algorithms, differentiating between supervised and unsupervised models. It guides readers through configuring and training models using scikit-learn while comparing various algorithms such as Logistic Regression, Decision Trees, and Random Forests. Performance metrics like accuracy, precision, recall, and F1-score are explained to evaluate model effectiveness. Additionally, it addresses real-time data collection from IoT sensors and integration with communication libraries. A simple graphical interface can be created using Tkinter or Flask to display results and set up failure prediction alerts. Finally, the book emphasizes the importance of testing software iterations for improvement while considering deployment options—local versus cloud—and security measures necessary for maintaining system integrity.`,
    pages: 320,
    language: "English",
    isbn: "B0DV2R31W6"
  },
  {
    id: 'predictive-maintenance-playbook',
    title: "The Predictive Maintenance Playbook: Strategies for Data Scientists Using Java and Python",
    subtitle: "Sistemas Preditivos",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Strategies for predictive maintenance",
    coverImage: "/images/books/playbook.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DVLKDD6K",
    category: "Sistemas Preditivos",
    summary: `The Predictive Maintenance Playbook: Strategies for Data Scientists Using Java and Python is a crucial resource for professionals aiming to implement predictive maintenance in industrial environments. As industries increasingly adopt data-driven approaches, the ability to foresee equipment failures has become essential for enhancing operational efficiency and reducing costs. The book begins by introducing the core concepts of predictive maintenance, emphasizing its relevance in the context of Industry 4.0 and the Internet of Things (IoT). It explores various data sources critical for predictive maintenance, including sensor data, historical records, and operational metrics. The text then delves into methodologies and algorithms pertinent to predictive analytics, offering insights into statistical techniques, machine learning models, and data preprocessing methods. Subsequent sections provide practical guidance on implementing solutions using Java and Python, featuring hands-on examples and case studies that demonstrate real-world applications. A significant focus is placed on data visualization and interpretation skills necessary for effectively communicating findings to stakeholders. The book also addresses common challenges encountered during implementation, providing actionable strategies to overcome these hurdles. Ultimately, this playbook serves not only as a technical manual but also as an inspirational guide for data scientists and engineers seeking innovation in their maintenance practices. By equipping readers with robust frameworks tailored to their needs, it aims to enhance the reliability and performance of critical assets through effective use of data science techniques.`,
    pages: 400,
    language: "English",
    isbn: "B0DVLKDD6K"
  }
];
