import { Book } from '../types/books';

export const books: Book[] = [
  {
    id: 'manutencao-java',
    title: "Manutenção Preditiva com Java: Um Guia Prático para Cientistas de Dados",
    subtitle: "Sistemas Preditivos",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Guia prático de manutenção preditiva com Java",
    coverImage: "https://m.media-amazon.com/images/I/41jz5zL0qDL._SY445_SX342_.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DVCZRW8M",
    category: "Sistemas Preditivos",
    summary: `O livro "Manutenção Preditiva com Java: Um Guia Prático para Cientistas de Dados" aborda a crescente importância da manutenção preditiva...`,
    pages: 300,
    language: "Português",
    isbn: "B0DVCZRW8M"
  },
  {
    id: 'manutencoes-python',
    title: "Como Prever manutenções Mecânicas com Python?",
    subtitle: "Manutenções Preditivas com Python (Sistemas Preditivos Livro 1)",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Manutenções Preditivas com Python",
    coverImage: "https://m.media-amazon.com/images/I/41KiZbwC3tL._SY445_SX342_.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DV519HDX",
    category: "Sistemas Preditivos",
    summary: `O livro "Como Prever Manutenções Mecânicas com Python?" aborda a crescente importância da manutenção preditiva no contexto industrial atual...`,
    pages: 280,
    language: "Português",
    isbn: "B0DV519HDX"
  },
  {
    id: 'python-predictive-insights',
    title: "Python for Predictive Insights: Code Your Way to Data Mastery",
    subtitle: "Sistemas Preditivos",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Master predictive analytics with Python",
    coverImage: "https://m.media-amazon.com/images/I/41h0RGUT7BL._SY445_SX342_.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DV2HBF1P",
    category: "Sistemas Preditivos",
    summary: `"Python for Predictive Insights: Code Your Way to Data Mastery" is a vital resource for anyone looking to harness the power of data through Python programming...`,
    pages: 350,
    language: "English",
    isbn: "B0DV2HBF1P"
  },
  {
    id: 'mastering-predictive-maintenance',
    title: "Mastering Predictive Maintenance: your Blueprint for Software",
    subtitle: "Sistemas Preditivos",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Blueprint for predictive maintenance software",
    coverImage: "https://m.media-amazon.com/images/I/41h0RGUT7BL._SY445_SX342_.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DV2R31W6",
    category: "Sistemas Preditivos",
    summary: `Mastering Predictive Maintenance: Your Blueprint for Software Development delves into the critical role of predictive maintenance in modern industry...`,
    pages: 320,
    language: "English",
    isbn: "B0DV2R31W6"
  },
  {
    id: 'predictive-maintenance-playbook',
    title: "The Predictive Maintenance Playbook: Strategies for Data Scientists Using Java and Python",
    subtitle: "Sistemas Preditivos",
    author: "Adjalma Machado Aguiar Junior",
    year: 2024,
    publisher: "Amazon",
    description: "Strategies for predictive maintenance",
    coverImage: "https://m.media-amazon.com/images/I/41h0RGUT7BL._SY445_SX342_.jpg",
    downloadUrl: "https://www.amazon.com.br/gp/product/B0DVLKDD6K",
    category: "Sistemas Preditivos",
    summary: `The Predictive Maintenance Playbook: Strategies for Data Scientists Using Java and Python is a crucial resource for professionals aiming to implement predictive maintenance in industrial environments...`,
    pages: 400,
    language: "English",
    isbn: "B0DVLKDD6K"
  }
]; 